cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    hudson:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$KTz7vNoK6D49DLagjs6HV.U/zFCpVQyYVSOfF7mguMWf7jf6qPEWC
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$qtvuP21heAgl3qqvghHOyO9btnX4WDkoXOTOIFWYkqMJIYPgx0N4S
pre-authorized:
  emails:
  - melsby@gmail.com
