cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$SmWOg2ACLTqBKuf54.JrW.0FE0p.nuBST8Ofj0uRx0/PmUu4ba0h.
    hudson:
      email: hudson@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Hudson
      password: $2b$12$IQtjCa.0mfmvLxA6ug2DXO1tmlL7PprL4h/UNs2TTMw29RbomYzwy
    laurama:
      email: lauramattos@fundacaolemann.org.br
      failed_login_attempts: 0
      logged_in: true
      name: Laura Mattos
      password: $2b$12$66JkX2/Do3qSWH41DbdVvur2Fgs3mpnrcZx3KmkdLS39kkMy0QDum
    marlondev:
      email: marlon@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Marlon
      password: $2b$12$7KGP3GQZJEvAZrt7.faKO.JK9h8MfPRkkMMZP.b6hNEWOAQYWNsXC
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$eMYzGQ1FZy.8r8/rKHTUj.LVWM.jcZWSybZuG8kVcG57IW.XaOpje
pre-authorized:
  emails:
  - melsby@gmail.com
